export const CONTACT_REQUEST_CREATED = 'CONTACT_REQUEST_CREATED';
export const CONTACT_REQUEST_ACCEPTED = 'CONTACT_REQUEST_ACCEPTED';

export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE';

export const USER_TYPING = 'USER_TYPING';
export const MESSAGE_CREATED = 'MESSAGE_CREATED';
